language: node_js
node_js:
  - "4"
  - "4.0"
  - "4.1"
  - "4.2"
  - "4.3"
  - "4.4"
  - "5"
  - "6"


before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm run update-webdriver
